openapi: 3.0.0
info:
  title: MATR_1.0.1+simulator.completeness
  version: 1.0.0

paths:
########################################################################################################################
#   MATR_1.0.1+simulator.completeness in static reference mode
########################################################################################################################
  /v1/provide-mac-table-of-all-devices:
    parameters:
      - $ref: "#/components/parameters/user"
      - $ref: "#/components/parameters/originator"
      - $ref: "#/components/parameters/x-correlator"
      - $ref: "#/components/parameters/trace-indicator"
      - $ref: "#/components/parameters/customer-journey"
    post:
      operationId: provideMacTableOfAllDevices
      summary: "Responses with a list of MAC tables of all connected devices."
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      responses:
        "200":
          description: "List of MAC tables of all connected devices provided."
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    mount-name:
                      type: string
                    own-mac-address:
                      type: string
                    egress-ltp-uuid:
                      type: string
                    original-ltp-name:
                      type: string
                    vlan-id:
                      type: integer
                    remote-mac-address:
                      type: string
                    time-stamp-of-data:
                      type: string
                example:
                  - mount-name: "305251234"
                    own-mac-address: "00:00:00:00:00:00"
                    egress-ltp-uuid: "305251234+mac-inf-1234"
                    original-ltp-name: "eth-1-0-3"
                    vlan-id: 17
                    remote-mac-address: "01:01:01:01:01:01"
                    time-stamp-of-data: "2010-11-20T14:00:00+01:00"
                  - mount-name: "30525999"
                    own-mac-address: "FF:00:11:00:00:00"
                    egress-ltp-uuid: "305251234+mac-inf-1234"
                    original-ltp-name: "eth-1-0-3"
                    vlan-id: 17
                    remote-mac-address: "01:01:01:01:01:01"
                    time-stamp-of-data: "2010-11-20T14:00:00+01:00"
          headers:
            x-correlator:
              schema:
                type: string
            exec-time:
              schema:
                type: integer
            backend-time:
              schema:
                type: integer
            life-cycle-state:
              schema:
                type: string
                enum:
                  - "EXPERIMENTAL"
                  - "OPERATIONAL"
                  - "DEPRECATED"
                  - "OBSOLETE"
                  - "UNKNOWN"
                  - "NOT_YET_DEFINED"
        "400":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "401":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "403":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "404":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "500":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        default:
          $ref: "#/components/responses/responseForErroredServiceRequests"
  /v1/provide-mac-table-of-specific-device:
    parameters:
      - $ref: "#/components/parameters/user"
      - $ref: "#/components/parameters/originator"
      - $ref: "#/components/parameters/x-correlator"
      - $ref: "#/components/parameters/trace-indicator"
      - $ref: "#/components/parameters/customer-journey"
    post:
      operationId: provideMacTableOfSpecificDevice
      summary: "Responses with the MAC table of a specific device."
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - mount-name
              properties:
                mount-name:
                  type: string
      responses:
        "200":
          description: "MAC table for specific device provided."
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    mount-name:
                      type: string
                    own-mac-address:
                      type: string
                    egress-ltp-uuid:
                      type: string
                    original-ltp-name:
                      type: string
                    vlan-id:
                      type: integer
                    remote-mac-address:
                      type: string
                    time-stamp-of-data:
                      type: string
                example:
                  - mount-name: "305251234"
                    own-mac-address: "00:00:00:00:00:00"
                    egress-ltp-uuid: "305251234+mac-inf-1234"
                    original-ltp-name: "eth-1-0-3"
                    vlan-id: 17
                    remote-mac-address: "01:01:01:01:01:01"
                    time-stamp-of-data: "2010-11-20T14:00:00+01:00"
                  - mount-name: "305251234"
                    own-mac-address: "00:00:00:00:00:00"
                    egress-ltp-uuid: "305251234+mac-inf-1234"
                    original-ltp-name: "eth-1-0-3"
                    vlan-id: 17
                    remote-mac-address: "FF:01:01:01:01:01"
                    time-stamp-of-data: "2010-11-20T14:00:00+01:00"
          headers:
            x-correlator:
              schema:
                type: string
            exec-time:
              schema:
                type: integer
            backend-time:
              schema:
                type: integer
            life-cycle-state:
              schema:
                type: string
                enum:
                  - "EXPERIMENTAL"
                  - "OPERATIONAL"
                  - "DEPRECATED"
                  - "OBSOLETE"
                  - "UNKNOWN"
                  - "NOT_YET_DEFINED"
        "400":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "401":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "403":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "404":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "500":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        default:
          $ref: "#/components/responses/responseForErroredServiceRequests"
  /v1/read-current-mac-table-from-device:
    parameters:
      - $ref: "#/components/parameters/user"
      - $ref: "#/components/parameters/originator"
      - $ref: "#/components/parameters/x-correlator"
      - $ref: "#/components/parameters/trace-indicator"
      - $ref: "#/components/parameters/customer-journey"
    post:
      operationId: readCurrentMacTableFromDevice
      summary: "Responses with the current MAC table of a specific device."
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              anyOf:
                - description: "bare update of elasticsearch"
                  type: object
                  required:
                    - mount-name
                  properties:
                    mount-name:
                      type: string
                - description: "update of elasticsearch and response to the requestor"
                  type: object
                  required:
                    - mount-name
                    - requestor-protocol
                    - requestor-address
                    - requestor-port
                    - requestor-receive-operation
                  properties:
                    mount-name:
                      type: string
                    requestor-protocol:
                      type: string
                      enum:
                        - "HTTP"
                        - "HTTPS"
                    requestor-address:
                      type: object
                      minProperties: 1
                      maxProperties: 1
                      additionalProperties: false
                      properties:
                        ip-address:
                          type: object
                          minProperties: 1
                          additionalProperties: false
                          properties:
                            ipv-4-address:
                              type: string
                              pattern: '^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
                        domain-name:
                          type: string
                          pattern: '^([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,}$'
                    requestor-port:
                      type: integer
                    requestor-receive-operation:
                      type: string
      responses:
        "200":
          description: "Request for current MAC table received, response request will be sent after collecting all data."
          content:
            application/json:
              schema:
                type: object
                required:
                  - request-id
                properties:
                  request-id:
                    type: string
                example:
                  request-id: "305251234-101120-1400"
          headers:
            x-correlator:
              schema:
                type: string
            exec-time:
              schema:
                type: integer
            backend-time:
              schema:
                type: integer
            life-cycle-state:
              schema:
                type: string
                enum:
                  - "EXPERIMENTAL"
                  - "OPERATIONAL"
                  - "DEPRECATED"
                  - "OBSOLETE"
                  - "UNKNOWN"
                  - "NOT_YET_DEFINED"
        "204":
          description: "Request for current MAC table received, elasticsearch will be updated."
          headers:
            x-correlator:
              schema:
                type: string
            exec-time:
              schema:
                type: integer
            backend-time:
              schema:
                type: integer
            life-cycle-state:
              schema:
                type: string
                enum:
                  - "EXPERIMENTAL"
                  - "OPERATIONAL"
                  - "DEPRECATED"
                  - "OBSOLETE"
                  - "UNKNOWN"
                  - "NOT_YET_DEFINED"
        "400":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "401":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "403":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "404":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "500":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        default:
          $ref: "#/components/responses/responseForErroredServiceRequests"
  /v1/provide-list-of-network-element-interfaces-on-path:
    parameters:
      - $ref: "#/components/parameters/user"
      - $ref: "#/components/parameters/originator"
      - $ref: "#/components/parameters/x-correlator"
      - $ref: "#/components/parameters/trace-indicator"
      - $ref: "#/components/parameters/customer-journey"
    post:
      operationId: provideListOfNetworkElementInterfacesOnPath
      summary: "Provides unsorted list of network element interfaces on path to specific MAC address."
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - target-mac-address
              properties:
                target-mac-address:
                  type: string
                  pattern: "^[a-fA-F0-9]{2}(:[a-fA-F0-9]{2}){5}$"
      responses:
        "200":
          description: "List of network element interfaces that lead to a specific MAC address provided."
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    target-mac-address:
                      type: string
                    mount-name:
                      type: string
                    original-ltp-name:
                      type: string
                    vlan-id:
                      type: integer
                    time-stamp-of-data:
                      type: string
                example:
                  - target-mac-address: "01:01:01:01:01:01"
                    mount-name: "305251234"
                    original-ltp-name: "eth-1-0-3"
                    vlan-id: 430
                    time-stamp-of-data: "2010-11-20T14:00:00+01:00"
                  - target-mac-address: "01:01:01:01:01:01"
                    mount-name: "305259999"
                    original-ltp-name: "eth-2-0-3"
                    vlan-id: 430
                    time-stamp-of-data: "2010-11-20T14:30:00+01:00"
          headers:
            x-correlator:
              schema:
                type: string
            exec-time:
              schema:
                type: integer
            backend-time:
              schema:
                type: integer
            life-cycle-state:
              schema:
                type: string
                enum:
                  - "EXPERIMENTAL"
                  - "OPERATIONAL"
                  - "DEPRECATED"
                  - "OBSOLETE"
                  - "UNKNOWN"
                  - "NOT_YET_DEFINED"
        "400":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "401":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "403":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "404":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "500":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        default:
          $ref: "#/components/responses/responseForErroredServiceRequests"
  /v1/provide-list-of-network-element-interfaces-on-path-in-generic-representation:
    parameters:
      - $ref: "#/components/parameters/user"
      - $ref: "#/components/parameters/originator"
      - $ref: "#/components/parameters/x-correlator"
      - $ref: "#/components/parameters/trace-indicator"
      - $ref: "#/components/parameters/customer-journey"
    post:
      operationId: provideListOfNetworkElementInterfacesOnPathInGenericRepresentation
      summary: "Provides unsorted list of network element interfaces on path to specific MAC address in generic representation."
      tags:
        - IndividualServices
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - input-value-list
              properties:
                input-value-list:
                  type: array
                  items:
                    type: object
                    required:
                      - field-name
                      - field-value
                    properties:
                      field-name:
                        type: string
                      field-value:
                        type: string
      responses:
        "200":
          description: "List of network element interfaces, that lead to a certain MAC address are provided in generic representation."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/genericRepresentation"
                example:
                  response-value-list:
                    - field-name: "listOfNetworkElementInterfacesOnPath"
                      value: "509251234:eth-1-0-3;509251234:EX-1-1;509253333:eth-1-3-3;509253333:EX-1-0"
                      datatype: "string"
                  consequent-action-list:
          headers:
            x-correlator:
              schema:
                type: string
            exec-time:
              schema:
                type: integer
            backend-time:
              schema:
                type: integer
            life-cycle-state:
              schema:
                type: string
                enum:
                  - "EXPERIMENTAL"
                  - "OPERATIONAL"
                  - "DEPRECATED"
                  - "OBSOLETE"
                  - "UNKNOWN"
                  - "NOT_YET_DEFINED"
        "400":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "401":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "403":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "404":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "500":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        default:
          $ref: "#/components/responses/responseForErroredServiceRequests"


########################################################################################################################
#   Generic Simulator (generic examples, but all response codes)
########################################################################################################################
  /generic/v1/provide-mac-table-of-all-devices:
    parameters:
      - $ref: "#/components/parameters/user"
      - $ref: "#/components/parameters/originator"
      - $ref: "#/components/parameters/x-correlator"
      - $ref: "#/components/parameters/trace-indicator"
      - $ref: "#/components/parameters/customer-journey"
    post:
      operationId: provideMacTableOfAllDevices
      summary: "Responses with a list of MAC tables of all connected devices."
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      responses:
        "200":
          description: "List of MAC tables of all connected devices provided."
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    mount-name:
                      type: string
                    own-mac-address:
                      type: string
                    egress-ltp-uuid:
                      type: string
                    original-ltp-name:
                      type: string
                    vlan-id:
                      type: integer
                    remote-mac-address:
                      type: string
                    time-stamp-of-data:
                      type: string
                example:
                  - mount-name: 'string'
                    own-mac-address: 'string'
                    egress-ltp-uuid: 'string'
                    original-ltp-name: 'string'
                    vlan-id: 0
                    remote-mac-address: 'string'
                    time-stamp-of-data: 'string'
          headers:
            x-correlator:
              schema:
                type: string
            exec-time:
              schema:
                type: integer
            backend-time:
              schema:
                type: integer
            life-cycle-state:
              schema:
                type: string
                enum:
                  - "EXPERIMENTAL"
                  - "OPERATIONAL"
                  - "DEPRECATED"
                  - "OBSOLETE"
                  - "UNKNOWN"
                  - "NOT_YET_DEFINED"
        "400":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "401":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "403":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "404":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "500":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        default:
          $ref: "#/components/responses/responseForErroredServiceRequests"
  /generic/v1/provide-mac-table-of-specific-device:
    parameters:
      - $ref: "#/components/parameters/user"
      - $ref: "#/components/parameters/originator"
      - $ref: "#/components/parameters/x-correlator"
      - $ref: "#/components/parameters/trace-indicator"
      - $ref: "#/components/parameters/customer-journey"
    post:
      operationId: provideMacTableOfSpecificDevice
      summary: "Responses with the MAC table of a specific device."
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - mount-name
              properties:
                mount-name:
                  type: string
      responses:
        "200":
          description: "MAC table for specific device provided."
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    mount-name:
                      type: string
                    own-mac-address:
                      type: string
                    egress-ltp-uuid:
                      type: string
                    original-ltp-name:
                      type: string
                    vlan-id:
                      type: integer
                    remote-mac-address:
                      type: string
                    time-stamp-of-data:
                      type: string
                example:
                  - mount-name: 'string'
                    own-mac-address: 'string'
                    egress-ltp-uuid: 'string'
                    original-ltp-name: 'string'
                    vlan-id: 0
                    remote-mac-address: 'string'
                    time-stamp-of-data: 'string'
          headers:
            x-correlator:
              schema:
                type: string
            exec-time:
              schema:
                type: integer
            backend-time:
              schema:
                type: integer
            life-cycle-state:
              schema:
                type: string
                enum:
                  - "EXPERIMENTAL"
                  - "OPERATIONAL"
                  - "DEPRECATED"
                  - "OBSOLETE"
                  - "UNKNOWN"
                  - "NOT_YET_DEFINED"
        "400":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "401":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "403":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "404":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "500":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        default:
          $ref: "#/components/responses/responseForErroredServiceRequests"
  /generic/v1/read-current-mac-table-from-device:
    parameters:
      - $ref: "#/components/parameters/user"
      - $ref: "#/components/parameters/originator"
      - $ref: "#/components/parameters/x-correlator"
      - $ref: "#/components/parameters/trace-indicator"
      - $ref: "#/components/parameters/customer-journey"
    post:
      operationId: readCurrentMacTableFromDevice
      summary: "Responses with the current MAC table of a specific device."
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              anyOf:
                - description: "bare update of elasticsearch"
                  type: object
                  required:
                    - mount-name
                  properties:
                    mount-name:
                      type: string
                - description: "update of elasticsearch and response to the requestor"
                  type: object
                  required:
                    - mount-name
                    - requestor-protocol
                    - requestor-address
                    - requestor-port
                    - requestor-receive-operation
                  properties:
                    mount-name:
                      type: string
                    requestor-protocol:
                      type: string
                      enum:
                        - "HTTP"
                        - "HTTPS"
                    requestor-address:
                      type: object
                      minProperties: 1
                      maxProperties: 1
                      additionalProperties: false
                      properties:
                        ip-address:
                          type: object
                          minProperties: 1
                          additionalProperties: false
                          properties:
                            ipv-4-address:
                              type: string
                              pattern: '^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
                        domain-name:
                          type: string
                          pattern: '^([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,}$'
                    requestor-port:
                      type: integer
                    requestor-receive-operation:
                      type: string
      responses:
        "200":
          description: "Request for current MAC table received, response request will be sent after collecting all data."
          content:
            application/json:
              schema:
                type: object
                required:
                  - request-id
                properties:
                  request-id:
                    type: string
                example:
                  request-id: 'string'
          headers:
            x-correlator:
              schema:
                type: string
            exec-time:
              schema:
                type: integer
            backend-time:
              schema:
                type: integer
            life-cycle-state:
              schema:
                type: string
                enum:
                  - "EXPERIMENTAL"
                  - "OPERATIONAL"
                  - "DEPRECATED"
                  - "OBSOLETE"
                  - "UNKNOWN"
                  - "NOT_YET_DEFINED"
        "204":
          description: "Request for current MAC table received, elasticsearch will be updated."
          headers:
            x-correlator:
              schema:
                type: string
            exec-time:
              schema:
                type: integer
            backend-time:
              schema:
                type: integer
            life-cycle-state:
              schema:
                type: string
                enum:
                  - "EXPERIMENTAL"
                  - "OPERATIONAL"
                  - "DEPRECATED"
                  - "OBSOLETE"
                  - "UNKNOWN"
                  - "NOT_YET_DEFINED"
        "400":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "401":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "403":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "404":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "500":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        default:
          $ref: "#/components/responses/responseForErroredServiceRequests"
  /generic/v1/provide-list-of-network-element-interfaces-on-path:
    parameters:
      - $ref: "#/components/parameters/user"
      - $ref: "#/components/parameters/originator"
      - $ref: "#/components/parameters/x-correlator"
      - $ref: "#/components/parameters/trace-indicator"
      - $ref: "#/components/parameters/customer-journey"
    post:
      operationId: provideListOfNetworkElementInterfacesOnPath
      summary: "Provides unsorted list of network element interfaces on path to specific MAC address."
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - target-mac-address
              properties:
                target-mac-address:
                  type: string
                  pattern: "^[a-fA-F0-9]{2}(:[a-fA-F0-9]{2}){5}$"
      responses:
        "200":
          description: "List of network element interfaces that lead to a specific MAC address provided."
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    target-mac-address:
                      type: string
                    mount-name:
                      type: string
                    original-ltp-name:
                      type: string
                    vlan-id:
                      type: integer
                    time-stamp-of-data:
                      type: string
                example:
                  - target-mac-address: 'string'
                    mount-name: 'string'
                    original-ltp-name: 'string'
                    vlan-id: 0
                    time-stamp-of-data: 'string'
          headers:
            x-correlator:
              schema:
                type: string
            exec-time:
              schema:
                type: integer
            backend-time:
              schema:
                type: integer
            life-cycle-state:
              schema:
                type: string
                enum:
                  - "EXPERIMENTAL"
                  - "OPERATIONAL"
                  - "DEPRECATED"
                  - "OBSOLETE"
                  - "UNKNOWN"
                  - "NOT_YET_DEFINED"
        "400":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "401":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "403":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "404":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "500":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        default:
          $ref: "#/components/responses/responseForErroredServiceRequests"
  /generic/v1/provide-list-of-network-element-interfaces-on-path-in-generic-representation:
    parameters:
      - $ref: "#/components/parameters/user"
      - $ref: "#/components/parameters/originator"
      - $ref: "#/components/parameters/x-correlator"
      - $ref: "#/components/parameters/trace-indicator"
      - $ref: "#/components/parameters/customer-journey"
    post:
      operationId: provideListOfNetworkElementInterfacesOnPathInGenericRepresentation
      summary: "Provides unsorted list of network element interfaces on path to specific MAC address in generic representation."
      tags:
        - IndividualServices
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - input-value-list
              properties:
                input-value-list:
                  type: array
                  items:
                    type: object
                    required:
                      - field-name
                      - field-value
                    properties:
                      field-name:
                        type: string
                      field-value:
                        type: string
      responses:
        "200":
          description: "List of network element interfaces, that lead to a certain MAC address are provided in generic representation."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/genericRepresentation"
                example:
                  response-value-list:
                    - field-name: 'string'
                      value: 'string'
                      datatype: 'string'
                  consequent-action-list:
                    - label: 'string'
                      request: 'string'
                      input-value-list:
                        - field-name: 'string'
                          unit: 'string'
                      display-in-new-browser-window: true
          headers:
            x-correlator:
              schema:
                type: string
            exec-time:
              schema:
                type: integer
            backend-time:
              schema:
                type: integer
            life-cycle-state:
              schema:
                type: string
                enum:
                  - "EXPERIMENTAL"
                  - "OPERATIONAL"
                  - "DEPRECATED"
                  - "OBSOLETE"
                  - "UNKNOWN"
                  - "NOT_YET_DEFINED"
        "400":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "401":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "403":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "404":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        "500":
          $ref: "#/components/responses/responseForErroredServiceRequests"
        default:
          $ref: "#/components/responses/responseForErroredServiceRequests"


########################################################################################################################
#   Common Components
########################################################################################################################
components:
  parameters:
    user:
      name: user
      in: header
      required: true
      schema:
        type: string
        example: "User Name"
      description: "User identifier from the system starting the service call"
    originator:
      name: originator
      in: header
      required: true
      schema:
        type: string
        minLength: 3
        example: "Resolver"
      description: >
        'Identification for the system consuming the API, as defined in
         [/core-model-1-4:control-construct/logical-termination-point={uuid}/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-configuration/application-name]'
    x-correlator:
      name: x-correlator
      in: header
      required: true
      schema:
        type: string
        pattern: "^[0-9A-Fa-f]{8}(?:-[0-9A-Fa-f]{4}){3}-[0-9A-Fa-f]{12}$"
        description: "Empty string accepted from external applications."
        example: "550e8400-e29b-11d4-a716-446655440000"
      description: "UUID for the service execution flow that allows to correlate requests and responses"
    trace-indicator:
      name: trace-indicator
      in: header
      required: true
      schema:
        type: string
        pattern: '^([0-9]+)(\.([0-9]+))*$'
        description: "Empty string accepted from external applications."
        example: "1.3.1"
      description: "Sequence of request numbers along the flow"
    customer-journey:
      name: customer-journey
      in: header
      required: true
      schema:
        type: string
        example: "Unknown value"
      description: "Holds information supporting customer’s journey to which the execution applies"
  responses:
    responseForErroredServiceRequests:
      description: "Response in case of errored service requests"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errorDescription"
      headers:
        x-correlator:
          schema:
            type: string
            pattern: "^[0-9A-Fa-f]{8}(?:-[0-9A-Fa-f]{4}){3}-[0-9A-Fa-f]{12}$"
            example: "550e8400-e29b-11d4-a716-446655440000"
          description: "UUID for the service execution flow that allows to correlate requests and responses. Its value must be identical at the response compared with its corresponding request"
        exec-time:
          schema:
            type: integer
            example: 1100
          description: "Value written by the service provider, reporting the total elapsed time for the execution, including all the additional processing needed to retrieve the data from the backend service. Expressed in milliseconds"
        backend-time:
          schema:
            type: integer
            example: 850
          description: "Value written by the service provider, reporting the elapsed time for data retrieval from the backend (service invocation, database access…). Expressed in milliseconds"
    responseForErroredOamRequests:
      description: "Response in case of errored OaM requests"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errorDescription"
  schemas:
    errorDescription:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    genericRepresentation:
      type: object
      required:
        - response-value-list
        - consequent-action-list
      properties:
        response-value-list:
          type: array
          items:
            type: object
            required:
              - field-name
              - value
              - datatype
            properties:
              field-name:
                type: string
                description: >
                  'Field name
                  from [/core-model-1-4:control-construct/profile-collection/profile=matr-1-0-0-response-p-*/response-profile-1-0:response-profile-pac/response-profile-capability/field-name]'
              value:
                type: string
                description: >
                  'Field value
                  from [/core-model-1-4:control-construct/profile-collection/profile=matr-1-0-0-response-p-*/response-profile-1-0:response-profile-pac/response-profile-configuration/value]'
              datatype:
                type: string
                description: >
                  'Field datatype
                  from [/core-model-1-4:control-construct/profile-collection/profile=matr-1-0-0-response-p-*/response-profile-1-0:response-profile-pac/response-profile-capability/datatype]'
        consequent-action-list:
          type: array
          items:
            type: object
            required:
              - label
              - request
              - display-in-new-browser-window
            properties:
              label:
                type: string
                description: >
                  'Label that shall be presented on the button
                  from [/core-model-1-4:control-construct/profile-collection/profile=matr-1-0-0-action-p-*/action-profile-1-0:action-profile-pac/action-profile-capability/label]'
              request:
                type: string
                description: >
                  'Request that shall be called, when button gets pressed
                  from
                  [{/core-model-1-4:control-construct/logical-termination-point=matr-1-0-0-tcp-s-*/layer-protocol=0/tcp-server-interface-1-0:tcp-server-interface-pac/tcp-server-interface-configuration/local-protocol}]
                  ://
                  [{/core-model-1-4:control-construct/logical-termination-point=matr-1-0-0-tcp-s-*/layer-protocol=0/tcp-server-interface-1-0:tcp-server-interface-pac/tcp-server-interface-configuration/local-address/ipv-4-address}
                  or
                  {/core-model-1-4:control-construct/logical-termination-point=matr-1-0-0-tcp-s-*/layer-protocol=0/tcp-server-interface-1-0:tcp-server-interface-pac/tcp-server-interface-configuration/local-address/domain-name}]
                  :
                  [{/core-model-1-4:control-construct/logical-termination-point=matr-1-0-0-tcp-s-*/layer-protocol=0/tcp-server-interface-1-0:tcp-server-interface-pac/tcp-server-interface-configuration/local-port}]
                  [{/core-model-1-4:control-construct/profile-collection/profile=matr-1-0-0-action-p-*/action-profile-1-0:action-profile-pac/action-profile-configuration/consequent-operation-reference}]'
              input-value-list:
                type: array
                items:
                  type: object
                  required:
                    - field-name
                  properties:
                    field-name:
                      type: string
                      description: >
                        'Name of an input value required for executing the Request
                        from [/core-model-1-4:control-construct/profile-collection/profile=matr-1-0-0-action-p-*/action-profile-1-0:action-profile-pac/action-profile-capability/input-value-list=*/name]'
                    unit:
                      type: string
                      description: >
                        'Unit of an input value required for executing the Request
                        from [/core-model-1-4:control-construct/profile-collection/profile=matr-1-0-0-action-p-*/action-profile-1-0:action-profile-pac/action-profile-capability/input-value-list=*/unit]'
              display-in-new-browser-window:
                type: boolean
                description: >
                  'True in case Request shall be represented in a new browser window
                  from [/core-model-1-4:control-construct/profile-collection/profile=matr-1-0-0-action-p-*/action-profile-1-0:action-profile-pac/action-profile-capability/display-in-new-browser-window]'
    logicalTerminationPoint:
      type: object
      required:
        - uuid
        - ltp-direction
        - client-ltp
        - server-ltp
        - layer-protocol
      properties:
        uuid:
          type: string
        ltp-direction:
          type: string
        client-ltp:
          type: array
          uniqueItems: true
          items:
            type: string
        server-ltp:
          type: array
          uniqueItems: true
          items:
            type: string
        layer-protocol:
          type: array
          minItems: 1
          maxItems: 1
          items:
            oneOf:
              - description: "operation server"
                type: object
                required:
                  - local-id
                  - layer-protocol-name
                  - operation-server-interface-1-0:operation-server-interface-pac
                properties:
                  local-id:
                    type: string
                  layer-protocol-name:
                    type: string
                  operation-server-interface-1-0:operation-server-interface-pac:
                    type: object
                    required:
                      - operation-server-interface-capability
                      - operation-server-interface-configuration
                    properties:
                      operation-server-interface-capability:
                        type: object
                        required:
                          - operation-name
                        properties:
                          operation-name:
                            type: string
                      operation-server-interface-configuration:
                        type: object
                        required:
                          - life-cycle-state
                        properties:
                          life-cycle-state:
                            type: string
              - description: "http server"
                type: object
                required:
                  - local-id
                  - layer-protocol-name
                  - http-server-interface-1-0:http-server-interface-pac
                properties:
                  local-id:
                    type: string
                  layer-protocol-name:
                    type: string
                  http-server-interface-1-0:http-server-interface-pac:
                    type: object
                    required:
                      - http-server-interface-capability
                    properties:
                      http-server-interface-capability:
                        type: object
                        required:
                          - application-name
                          - release-number
                          - data-update-period
                        properties:
                          application-name:
                            type: string
                          release-number:
                            type: string
                          data-update-period:
                            type: string
              - description: "tcp server"
                type: object
                required:
                  - local-id
                  - layer-protocol-name
                  - tcp-server-interface-1-0:tcp-server-interface-pac
                properties:
                  local-id:
                    type: string
                  layer-protocol-name:
                    type: string
                  tcp-server-interface-1-0:tcp-server-interface-pac:
                    type: object
                    required:
                      - tcp-server-interface-configuration
                    properties:
                      tcp-server-interface-configuration:
                        type: object
                        required:
                          - description
                          - local-protocol
                          - local-address
                          - local-port
                        properties:
                          description:
                            type: string
                          local-protocol:
                            type: string
                          local-address:
                            type: object
                            properties:
                              ipv-4-address:
                                type: string
                              domain-name:
                                type: string
                          local-port:
                            type: integer
              - description: "operation client"
                type: object
                required:
                  - local-id
                  - layer-protocol-name
                  - operation-client-interface-1-0:operation-client-interface-pac
                properties:
                  local-id:
                    type: string
                  layer-protocol-name:
                    type: string
                  operation-client-interface-1-0:operation-client-interface-pac:
                    type: object
                    required:
                      - operation-client-interface-configuration
                      - operation-client-interface-status
                    properties:
                      operation-client-interface-configuration:
                        type: object
                        required:
                          - operation-name
                        properties:
                          operation-name:
                            type: string
                      operation-client-interface-status:
                        type: object
                        required:
                          - operational-state
                          - life-cycle-state
                        properties:
                          operational-state:
                            type: string
                          life-cycle-state:
                            type: string
              - description: "elasticsearch client"
                type: object
                required:
                  - local-id
                  - layer-protocol-name
                  - elasticsearch-client-interface-1-0:elasticsearch-client-interface-pac
                properties:
                  local-id:
                    type: string
                  layer-protocol-name:
                    type: string
                  ? elasticsearch-client-interface-1-0:elasticsearch-client-interface-pac
                  : type: object
                    required:
                      - elasticsearch-client-interface-configuration
                      - elasticsearch-client-interface-status
                    properties:
                      elasticsearch-client-interface-configuration:
                        type: object
                        required:
                          - index-alias
                        properties:
                          index-alias:
                            type: string
                      elasticsearch-client-interface-status:
                        type: object
                        required:
                          - operational-state
                          - life-cycle-state
                        properties:
                          operational-state:
                            type: string
                          life-cycle-state:
                            type: string
              - description: "http client"
                type: object
                required:
                  - local-id
                  - layer-protocol-name
                  - http-client-interface-1-0:http-client-interface-pac
                properties:
                  local-id:
                    type: string
                  layer-protocol-name:
                    type: string
                  http-client-interface-1-0:http-client-interface-pac:
                    type: object
                    required:
                      - http-client-interface-configuration
                    properties:
                      http-client-interface-configuration:
                        type: object
                        required:
                          - application-name
                          - release-number
                        properties:
                          application-name:
                            type: string
                          release-number:
                            type: string
              - description: "tcp client"
                type: object
                required:
                  - local-id
                  - layer-protocol-name
                  - tcp-client-interface-1-0:tcp-client-interface-pac
                properties:
                  local-id:
                    type: string
                  layer-protocol-name:
                    type: string
                  tcp-client-interface-1-0:tcp-client-interface-pac:
                    type: object
                    required:
                      - tcp-client-interface-configuration
                    properties:
                      tcp-client-interface-configuration:
                        type: object
                        required:
                          - remote-protocol
                          - remote-address
                          - remote-port
                        properties:
                          remote-protocol:
                            type: string
                          remote-address:
                            type: object
                            properties:
                              ip-address:
                                type: object
                                properties:
                                  ipv-4-address:
                                    type: string
                              domain-name:
                                type: string
                          remote-port:
                            type: integer
    forwardingDomain:
      type: object
      required:
        - uuid
        - forwarding-construct
      properties:
        uuid:
          type: string
        forwarding-construct:
          type: array
          items:
            type: object
            required:
              - uuid
              - name
              - fc-port
            properties:
              uuid:
                type: string
              name:
                type: array
                items:
                  type: object
                  required:
                    - value-name
                    - value
                  properties:
                    value-name:
                      type: string
                    value:
                      type: string
              fc-port:
                type: array
                items:
                  type: object
                  required:
                    - local-id
                    - port-direction
                    - logical-termination-point
                  properties:
                    local-id:
                      type: string
                    port-direction:
                      type: string
                    logical-termination-point:
                      type: string
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: operation-key
    basicAuth:
      type: http
      scheme: basic
